// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddNativeApp(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function CreateDesktopShortcut(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetApps():Promise<Array<models.AppModel>>;

export function GetSystemApps():Promise<Array<models.SystemApp>>;

export function LaunchApp(arg1:string,arg2:string):Promise<boolean>;

export function RemoveNativeApp(arg1:string):Promise<boolean>;

export function SelectExecutable():Promise<string>;

export function TogglePermission(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<boolean>;
