// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNativeApp(arg1, arg2, arg3) {
  return window['go']['core']['App']['AddNativeApp'](arg1, arg2, arg3);
}

export function CreateDesktopShortcut(arg1, arg2, arg3) {
  return window['go']['core']['App']['CreateDesktopShortcut'](arg1, arg2, arg3);
}

export function GetApps() {
  return window['go']['core']['App']['GetApps']();
}

export function GetSystemApps() {
  return window['go']['core']['App']['GetSystemApps']();
}

export function LaunchApp(arg1, arg2) {
  return window['go']['core']['App']['LaunchApp'](arg1, arg2);
}

export function LaunchNativeApp(arg1) {
  return window['go']['core']['App']['LaunchNativeApp'](arg1);
}

export function RemoveNativeApp(arg1) {
  return window['go']['core']['App']['RemoveNativeApp'](arg1);
}

export function SelectExecutable() {
  return window['go']['core']['App']['SelectExecutable']();
}

export function TogglePermission(arg1, arg2, arg3, arg4) {
  return window['go']['core']['App']['TogglePermission'](arg1, arg2, arg3, arg4);
}
